/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package be.zvz.kotlininside

import kotlin.test.Test
import kotlin.test.assertTrue

class KotlinInsideTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = KotlinInside()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
