/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package be.zvz.kotlininside

import be.zvz.kotlininside.api.article.ArticleList
import be.zvz.kotlininside.session.user.Anonymous
import kotlin.test.Test
import kotlin.test.assertNotNull

class KotlinInsideTest {
    @Test fun testGetArticle() {
        KotlinInside.createInstance(Anonymous("ㅇㅇ", "1234"), TestHttpInterface())
        val classUnderTest = ArticleList("hit", 1)
        assertNotNull(classUnderTest.getGallList()[0], "ArticleList.getGallList() must not be null")
    }
}
