/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package be.zvz.kotlininside

import be.zvz.kotlininside.value.Api

class KotlinInside {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
